OPTIONS = {
        'structure':  ['Blockchain', 'DAG', 'Hashgraph', 'Holochain', 'Tempo'],
        'openess':  ['Public', 'Private'],
        'consensus':  ['PoW', 'PoS', 'DPoS', 'PoA', 'PoWeight', 'BFT'],
        'hashing':  ['SHA-256', 'SHA-512', 'Scrypt', 'KECCAK-256',
                     'KECCAK-512', 'Ethash', 'X11', 'X17', 'myr-groestl',
                     'Lyra2rev2', 'blake2s', 'blake2b'],
        'random':  ['DRBG', 'CPRNG'],
        'digital signature':  ['ECDSA', 'DSA', 'elgamal128', 'elgamal256', 'GOST R 34.10-2012'],
}

LINKS = {
    'Blockchain': 'See `src/example_chain.py` for a good classic blockchain implementation',
    'DAG': 'https://github.com/thieman/py-dag',
    'Hashgraph': 'https://github.com/Lapin0t/py-swirld',
    'Holochain': 'https://github.com/holochain/holochain-rust',
    'Tempo': 'https://github.com/radixdlt/radnet',
    'Public': 'Depends on your implementation: https://masterthecrypto.com/public-vs-private-blockchain-whats-the-difference/',
    'Private': 'Depends on your implementation: https://masterthecrypto.com/public-vs-private-blockchain-whats-the-difference/',
    'PoW': 'https://github.com/csunny/py-bitcoin/blob/master/consensus/proof_of_work.py',
    'PoS': 'https://github.com/csunny/blockchain',
    'DPoS': 'https://github.com/DEADP0OL/DPoS-Slackbot',
    'PoA': 'https://github.com/poanetwork/wiki/wiki/POA-Network-Whitepaper',
    'PoWeight': 'Read https://filecoin.io/filecoin.pdf',
    'BFT': 'https://github.com/practicalbft/BFTList-client/tree/master/client',
    'SHA-256': 'https://github.com/thomdixon/pysha2/blob/master/sha2/sha256.py',
    'SHA-512': 'https://github.com/thomdixon/pysha2/blob/master/sha2/sha512.py',
    'Scrypt': 'https://github.com/ricmoo/pyscrypt',
    'KECCAK-256': 'https://pycryptodome.readthedocs.io/en/latest/src/hash/hash.html',
    'KECCAK-512': 'https://pycryptodome.readthedocs.io/en/latest/src/hash/hash.html',
    'Ethash': 'https://github.com/ethereum/ethash',
    'X11': 'https://pypi.org/project/x11_hash/',
    'X17': 'https://pypi.org/project/x17_hash/',
    'Lyra2rev2': 'https://github.com/straks/lyra2re-hash-python',
    'myr-groestl': 'https://github.com/vergecurrency/myr-groestl_hash',
    'blake2s': 'https://pycryptodome.readthedocs.io/en/latest/src/hash/hash.html',
    'blake2b': 'https://pycryptodome.readthedocs.io/en/latest/src/hash/hash.html',
    'DRBG': 'https://github.com/blubber/python-drbg/blob/master/drbg.py',
    'CPRNG': 'https://riptutorial.com/python/example/3857/create-cryptographically-secure-random-numbers',
    'ECDSA': 'https://github.com/warner/python-ecdsa',
    'DSA': 'https://github.com/rrottmann/pydsa',
    'elgamal128': 'https://github.com/RyanRiddle/elgamal',
    'elgamal256': 'https://github.com/RyanRiddle/elgamal',
    'GOST R 34.10-2012': 'https://pypi.org/project/pygost/',
}

TOINSTALL = {
    'SHA-256': 'algoritms/hashing/sha256',
    'SHA-512': 'algoritms/hashing/sha512',
    'Scrypt': 'algoritms/hashing/pyscrypt',
    'Ethash': 'algoritms/hashing/ethash',
    'KECCAK-256': 'algoritms/hashing/keccak',
    'KECCAK-512': 'algoritms/hashing/keccak',
    'Lyra2rev2': 'algoritms/hashing/lyra2re-hash-python',
    'myr-groestl': 'algoritms/hashing/myr-groestl_hash',
    'blake2s': 'algoritms/hashing/pycryptodome',
    'blake2b': 'algoritms/hashing/pycryptodome',
    'X11': 'algoritms/hashing/x11_hash',
    'X17': '.x17_hash',
    'ECDSA': 'algoritms/digital_signature/ecdsa',
    'elgamal128': 'algoritms/digital_signature/elgamal',
    'elgamal256': 'algoritms/digital_signature/elgamal',
    'GOST R 34.10-2012': 'algoritms/digital_signature/pygost',
    'PoW': 'skip',
}

INTERFACES = {
    'SHA-256': 'algoritms/hashing/__interfaces/sha256',
    'SHA-512': 'algoritms/hashing/__interfaces/sha512',
    'Scrypt': 'algoritms/hashing/__interfaces/pyscrypt',
    'Ethash': 'algoritms/hashing/__interfaces/ethash',
    'KECCAK-256': 'algoritms/hashing/__interfaces/keccak256',
    'KECCAK-512': 'algoritms/hashing/__interfaces/keccak512',
    'Lyra2rev2': 'algoritms/hashing/__interfaces/lyra2re-hash-python',
    'myr-groestl': 'algoritms/hashing/__interfaces/myr-groestl_hash',
    'blake2s': 'algoritms/hashing/__interfaces/blake2s',
    'blake2b': 'algoritms/hashing/__interfaces/blake2b',
    'ECDSA': 'algoritms/digital_signature/__interfaces/ecdsa',
    'elgamal128': 'algoritms/digital_signature/__interfaces/elgamal128',
    'elgamal256': 'algoritms/digital_signature/__interfaces/elgamal256',
    'GOST R 34.10-2012': 'algoritms/digital_signature/__interfaces/pygost',
    'X11': 'algoritms/hashing/__interfaces/x11',
    'X17': 'algoritms/hashing/__interfaces/x17',
    # 'PoW': '',
}
